"""Write the human review of everything the books disagree with -> data/reference/book_review.md (+ .csv per section).

    python data/review_book_checks.py

Sections: (1) Curtis 1994 note class vs dataset2 Volatility_Class (with Carles' class where he lists the material);
(2) potency classes vs Curtis odour strength (extremes) and Ohloff landmark dosages; (3) Tisserand & Young dermal maxima
vs what the engine allows a natural at 100 % formula; (4) Tisserand Ch 13 vs Ch 14 constituent bounds; (5) every row a
human still has to sign off (Decided_By = ai). Nothing here changes data — it is the list to decide on.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from load_data import load_all  # noqa: E402
from zone_b_chemistry.safety_engine import check_formula  # noqa: E402

OUT = HERE / "reference" / "book_review.md"


def md_table(df: pd.DataFrame, cols: list[str]) -> str:
    if df.empty:
        return "_none_\n"
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str(r[c]).replace("|", "/") for c in cols) + " |")
    return "\n".join(lines) + "\n"


def main() -> int:
    data = load_all()
    parts = ["# Book review — what the reference texts disagree with (generated by data/review_book_checks.py)\n",
             "Every line cites its page. Nothing here has been applied automatically except the three potency labels that were AI guesses "
             "contradicted by Curtis (Heliotropin, Cistus Oil, p-Cresyl phenylacetate) and Patchouli (Ohloff). Decide, then edit the CSV named in each section.\n"]

    # 1. Curtis layer vs dataset2 (+ Carles)
    carles = pd.read_csv(HERE / "reference" / "carles_volatility_table.csv", dtype=str, keep_default_na=False)
    carles_of = {r.Dataset2_Name: r.Carles_Class for r in carles.itertuples() if r.Dataset2_Name}
    c = data.curtis_check.copy()
    lay = c[~c["Layer_Agrees"]].copy()
    lay["Carles"] = lay["Dataset2_Name"].map(lambda n: carles_of.get(n, ""))
    lay["Page"] = lay["Source"].str.extract(r"(PDF p\.\d+)")
    parts.append(f"## 1. Volatility_Class vs Curtis' 'usual function' ({len(lay)} of {len(c)} matched materials disagree)\n\n"
                 "Edit `note_field_overrides.csv` (Field = Volatility_Class) if you side with Curtis. Where Carles is listed he is the third opinion.\n\n"
                 + md_table(lay, ["Dataset2_Name", "Volatility_Class", "Curtis_Class", "Carles", "Page"]))
    lay.to_csv(HERE / "reference" / "book_review_layers.csv", index=False)

    # 2. potency
    inten = c[~c["Intensity_Agrees"]]
    oh = data.ohloff_potency_check
    ohb = oh[~oh["Agrees"]] if len(oh) else oh
    parts.append(f"## 2. Odor_Strength (dosing class) vs the books\n\nCurtis' bold figure is odour strength of the neat material, dataset2's class is a "
                 f"dosing class — compared only at the extremes: {len(inten)} disagreements. Ohloff landmark dosages: {len(ohb)} disagreements of {len(oh)} checked.\n\n"
                 + md_table(inten, ["Dataset2_Name", "Odor_Strength", "Curtis_Intensity", "Source"]) + "\n" + md_table(ohb, ["Dataset2_Name", "Odor_Strength", "Ohloff_Pct", "Perfume"]))

    # 3. T&Y maxima vs engine
    rows = []
    ty = data.tisserand_maxima
    if len(ty):
        import re as _re
        for cas, g in ty.groupby("CAS"):
            names = data.notes.loc[data.notes["CAS"] == cas, "Note_Name"].drop_duplicates().tolist()
            for name in names:
                r = check_formula(pd.DataFrame([(name, cas, 100.0)], columns=["Note_Name", "CAS", "Pct"]), data)
                adv = [f for f in r.flags if f.code == "TY_ADVISORY" and f.note == name]
                allowed = float(r.formula.set_index("Note_Name").loc[name, "Pct"]) if r.verdict != "REJECT" and name in set(r.formula["Note_Name"]) else 0.0
                low = name.casefold()
                note_form = "Absolute" if "absolute" in low else ("Resinoid" if _re.search(r"resin|balsam", low) else "Essential oil")
                gg = g[(g["Form"] == note_form) | (g["Form"] == "")]
                gg = gg[gg["Grade_Word"].map(lambda w: (not w) or _re.search(rf"\b{_re.escape(str(w))}\b", low, _re.I) is not None)]
                if not len(gg):
                    continue
                best = gg.sort_values("TY_Max_Pct").iloc[0]
                rows.append({"Note": name, "CAS": cas, "Engine_Max_Pct_Neat": round(allowed, 3), "TY_Max_Pct": best["TY_Max_Pct"], "TY_Profile": best["Profile"],
                             "Form": best["Form"], "Basis": best["Basis_Constituent"], "Verdict": r.verdict, "Engine_Above_TY": bool(adv),
                             "Source": best["Source"]})
    tym = pd.DataFrame(rows)
    above = tym[tym["Engine_Above_TY"]] if len(tym) else tym
    parts.append(f"## 3. Tisserand & Young dermal maxima vs the engine ({len(above)} of {len(tym)} naturals: the engine allows more than T&Y recommend)\n\n"
                 "The engine applies IFRA Cat 4 + UK law + the constituent roll-up; T&Y's figure is an aromatherapy (whole-body) recommendation, usually stricter. "
                 "The safety engine already raises `TY_ADVISORY` for these; decide whether any should become a cap in `safety_caps.csv`.\n\n"
                 + md_table(above.sort_values("Note") if len(above) else above, ["Note", "Engine_Max_Pct_Neat", "TY_Max_Pct", "TY_Profile", "Form", "Basis", "Source"]))
    tym.to_csv(HERE / "reference" / "book_review_ty_maxima.csv", index=False)

    # 4. Ch 13 vs Ch 14
    ch14 = pd.read_csv(HERE / "reference" / "tisserand_ch14_sources.csv", dtype=str, keep_default_na=False)
    cons = pd.read_csv(HERE / "constituents.csv", dtype=str, keep_default_na=False)
    idx = {}
    for r in ch14.itertuples():
        key = (r.Constituent_CAS, "".join(ch for ch in r.Natural.casefold() if ch.isalpha()))
        idx[key] = max(idx.get(key, 0.0), float(r.Max_Pct))
    mism = []
    for r in cons.itertuples():
        import re
        m = re.search(r"profile '(.+?)'", r.Source)
        if not m:
            continue
        key = (r.Constituent_CAS, "".join(ch for ch in m.group(1).casefold() if ch.isalpha()))
        if key in idx and float(r.Fraction_Used) * 100 < idx[key] - max(0.5, 0.05 * idx[key]):
            mism.append({"Natural": r.Natural_Name, "Constituent": r.Constituent_Name, "Profile_Max": float(r.Fraction_Used) * 100, "Ch14_Max": idx[key], "Note": r.Note[:60]})
    parts.append(f"## 4. Tisserand Ch 13 profile bound below the Ch 14 'Sources' figure ({len(mism)} rows)\n\nSame book, two places. Benzoin: Ch 14 quotes the Sumatra grade for the "
                 "Siam row (grade-specific parse is right); blackcurrant: absolute vs oil.\n\n" + md_table(pd.DataFrame(mism), ["Natural", "Constituent", "Profile_Max", "Ch14_Max", "Note"]))

    # 5. sign-off list
    sign = []
    for f, col in (("note_additions.csv", "Decided_By"), ("note_field_overrides.csv", "Decided_By"), ("accord_edits.csv", "Decided_By"), ("cas_corrections.csv", "Decided_By"),
                   ("note_name_aliases.csv", "Decided_By"), ("accord_name_aliases.csv", "Decided_By")):
        p = HERE / f
        if p.exists():
            df = pd.read_csv(p, dtype=str, keep_default_na=False)
            if col in df.columns:
                n_ai = int(df[col].str.startswith("ai").sum())
                sign.append({"File": f, "Rows": len(df), "AI_decided": n_ai})
    parts.append("## 5. Rows a human must sign off (Decided_By starts with 'ai')\n\n" + md_table(pd.DataFrame(sign), ["File", "Rows", "AI_decided"]))
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"-> {OUT.relative_to(HERE.parent)}  ({len(lay)} layer, {len(inten)} intensity, {len(above)} T&Y-above, {len(mism)} ch14 rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
